driver:
  name: docker
  use_sudo: false
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36
platforms:
- name: centos-6.5
suites:
- name: default
  run_list:
  - recipe[RSEM]
  attributes:
