name 'RSEM'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures RSEM'
long_description 'Installs/Configures RSEM'
version '0.1.0'

supports 'centos', '= 6.5'

depends 'build-essential'
depends 'magic_shell'
depends 'git'
depends 'r'
depends 'git'
