name 'RSEM'
maintainer 'The Authors'
maintainer_email 'chef@eaglegenomics.com'
license 'Apache2'
description 'Installs/Configures RSEM'
long_description 'Installs/Configures RSEM'
version '1.0.0'

supports 'centos', '= 6.5'

depends 'build-essential'
depends 'magic_shell'
depends 'git'
depends 'r'
depends 'git'
